### ISSUE TITLE
MQBw Golf 8 R Dataset

### ISSUE THREAD

**Issue by heXc-me** [jilleb/MQB-FPA#104]
Attached an original DS from Golf 8 R MJ23, ANY changes Result in write Error with Online Tool (offline 010 Version unable to read)
I try to change FPA Set to remember last set´d FPA Mode ( Sport:Sport, Comfort:Comfort, Race:Race. ) Anyone can help here?

*Update*: Flashed via Odis E v17.x

[DA_0019_7208_5H0_2056_010FPA000003_MQB37WXRXGOLF.zip](https://github.com/jilleb/MQB-FPA/files/15213745/DA_0019_7208_5H0_2056_010FPA000003_MQB37WXRXGOLF.zip)

**Comment by Mr-MIBonk** [comment]
[2056.txt](https://github.com/jilleb/MQB-FPA/files/15213857/2056.txt)

For me, output is there and template works with your dataset...

**Comment by heXc-me** [comment]
when you´ve Time change  Sport:Sport, Comfort:Comfort, Race:Race. and convert to MK8 Dataset, i can/will try to write to Gateway..

**Comment by heXc-me** [comment]
Tested today on Table: Odis E failed with Job result: EXCEPTION_CAUGHT (1)
Original DS with 1 changed bit in chksum: Job result: EXCEPTION_CAUGHT (12)

so no chksum Problem...

**Comment by heXc-me** [comment]
because no one answered: Outputformat ONLY for Odis E is wrong (VCP and VCTool can handle it) (eg. 0x00,0x01... instead of 0001....). Quick´n dirty: Copy/ Paste Outputstring to new empty Excel sheet, use STRG-H 2 Times (replace 0x with nothing, same for , ). Copy Excelstring back to DA_0019_7208_5H0_2056_010FPA000003_MQB37WXRXGOLF ,

**Comment by sharkov69** [comment]
Could you post file that successfully flashed by Odis-E 17? I did your instructions but still got error

**Comment by Luis90-14** [comment]
Hi everyone, the driving profiles dataset. Can I use it on the golf 8 2.0tdi 116hp? gateway model  MQB2020  5WA907530Q. Best regards louis
