### ISSUE TITLE
Any way to get rid of the driving profile from mib upper corner?

### ISSUE THREAD

**Issue by JugihFIN** [jilleb/MQB-FPA#109]
Hi! 
love the ability for custom FPA-datasets!

while we’re at it, the upper left hand corner display of mib screen always shows static current fpa. 

The cars without fpa it shows the current address from navi.

Would there be any option to disable that static fpa display and let the address show?

if you disable Charisma from 5F, that’ll work, but it becomes impossible to edit individual profile and hybrid profiles as well from the screen.

**Comment by jilleb** [comment]
You can disable the charisma feature,  but that's about it.
