### ISSUE TITLE
Don't see enough bytes

### ISSUE THREAD

**Issue by HOSTED-POWER** [jilleb/MQB-FPA#91]
I tried it with obdeleven, selected 19 (Gateway) , but I can only go to by 0x29 or something under long coding.

What am I missing here? How do I map it to your parameters?

**Comment by jilleb** [comment]
Long coding is something other than datasets...
You cannot get your dataset by obd

**Comment by HOSTED-POWER** [comment]
Ok I was afraid already, what kind of tool do you need? Is it doable to find it ? :)
