### ISSUE TITLE
Fault After drive select

### ISSUE THREAD

**Issue by Libar19** [jilleb/MQB-FPA#92]
hello, after several attempts at odis online, I ask your opinion, I (on my gte) replaced my gateways with an AD, I have the driving modes and everything works fine. but I have a fault in the gateways "Local data bus Multi mount detected" impossible to make it go away, I also have a common fault in 17 and 5F: Limited operation due to missing message 0x23 BCMe

when I do an online coding with odis-Online, I have the defect: ERP0617E

Do you have any ideas ?

**Comment by jilleb** [comment]
I have no idea.. but GTE datasets can be a bit nasty.
