### ISSUE TITLE
Dataset wrong Adress

### ISSUE THREAD

**Issue by fritzelschnitzel** [jilleb/MQB-FPA#99]
Hi there,

I think there is an issue with the dataset adress when creating a Golf 8 dataset.
When editing a Golf 8 dataset and choosing VCP or Odis, this creates a dataset 
witch is for saving adress 0x0000B80. Isen´t that for Golf 7?
In earlier versions of the editor i always selectet 0x7208 and it worked fine.
![1](https://github.com/jilleb/MQB-FPA/assets/156140824/92c6996d-bf1a-4f75-92c2-3c6cfa69b58b)
![5](https://github.com/jilleb/MQB-FPA/assets/156140824/02f34fc9-c13b-4cf3-b540-cd00d8c7be79)

Also, when you switch the radio button to Golf 7 and back to Golf 8 the underlying radio buttons for the save format change from RAW/VCP/ODIS to RAW/Dataset Gen 2. (See upper/lower picture.)
![2](https://github.com/jilleb/MQB-FPA/assets/156140824/e6204967-ff45-468e-b2f3-910f12d41a4a)

Is the switch from  0x0007208 to  0x0000B80 intended or a bug? 

Best regards!
And a big THANK YOU for your awesome work!

**Comment by jilleb** [comment]
Saving to Golf8 format isnt fully functional yet.

**Comment by sharkov69** [comment]
I try to write FPA dataset to Golf 8 2024, do you know how to edit it manually to successully write? SFD protection off. Write with ODIS-E - got error. I changed only start address to 0x0007208.

**Comment by jilleb** [comment]
You can edit the offset manually in the xml

**Comment by sharkov69** [comment]
I tried checksum in Big endian and Little endian - both fail. I got GW 5WA907530L. Don't have original dateset by VIN, tried few templates from yours editor.
